#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : postgresql11
Version  : 11.14
Release  : 20
URL      : https://ftp.postgresql.org/pub/source/v11.14/postgresql-11.14.tar.gz
Source0  : https://ftp.postgresql.org/pub/source/v11.14/postgresql-11.14.tar.gz
Source1  : postgresql11-install.service
Source2  : postgresql11.service
Source3  : postgresql11.tmpfiles
Summary  : No detailed summary available
Group    : Development/Tools
License  : PostgreSQL TCL
Requires: postgresql11-bin = %{version}-%{release}
Requires: postgresql11-config = %{version}-%{release}
Requires: postgresql11-data = %{version}-%{release}
Requires: postgresql11-lib = %{version}-%{release}
Requires: postgresql11-libexec = %{version}-%{release}
Requires: postgresql11-license = %{version}-%{release}
Requires: postgresql11-services = %{version}-%{release}
BuildRequires : Linux-PAM-dev
BuildRequires : bison
BuildRequires : flex
BuildRequires : libxslt-bin
BuildRequires : ncurses-dev
BuildRequires : openssl-dev
BuildRequires : perl(IPC::Run)
BuildRequires : perl(Test::More)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3-dev
BuildRequires : readline-dev
BuildRequires : systemd-dev
BuildRequires : zlib-dev
Patch1: 0001-Move-socket-to-run-postgresql.patch

%description
PostgreSQL Database Management System
=====================================
This directory contains the source code distribution of the PostgreSQL
database management system.

%package bin
Summary: bin components for the postgresql11 package.
Group: Binaries
Requires: postgresql11-data = %{version}-%{release}
Requires: postgresql11-libexec = %{version}-%{release}
Requires: postgresql11-config = %{version}-%{release}
Requires: postgresql11-license = %{version}-%{release}
Requires: postgresql11-services = %{version}-%{release}

%description bin
bin components for the postgresql11 package.


%package config
Summary: config components for the postgresql11 package.
Group: Default

%description config
config components for the postgresql11 package.


%package data
Summary: data components for the postgresql11 package.
Group: Data

%description data
data components for the postgresql11 package.


%package dev
Summary: dev components for the postgresql11 package.
Group: Development
Requires: postgresql11-lib = %{version}-%{release}
Requires: postgresql11-bin = %{version}-%{release}
Requires: postgresql11-data = %{version}-%{release}
Provides: postgresql11-devel = %{version}-%{release}
Requires: postgresql11 = %{version}-%{release}

%description dev
dev components for the postgresql11 package.


%package lib
Summary: lib components for the postgresql11 package.
Group: Libraries
Requires: postgresql11-data = %{version}-%{release}
Requires: postgresql11-libexec = %{version}-%{release}
Requires: postgresql11-license = %{version}-%{release}

%description lib
lib components for the postgresql11 package.


%package libexec
Summary: libexec components for the postgresql11 package.
Group: Default
Requires: postgresql11-config = %{version}-%{release}
Requires: postgresql11-license = %{version}-%{release}

%description libexec
libexec components for the postgresql11 package.


%package license
Summary: license components for the postgresql11 package.
Group: Default

%description license
license components for the postgresql11 package.


%package services
Summary: services components for the postgresql11 package.
Group: Systemd services

%description services
services components for the postgresql11 package.


%prep
%setup -q -n postgresql-11.14
cd %{_builddir}/postgresql-11.14
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642638261
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --prefix=/usr/share/postgresql11 \
--bindir=/usr/libexec/postgresql11 \
--sysconfdir=/etc/postgresql11 \
--datadir=/usr/share/postgresql11 \
--includedir=/usr/include/postgresql11 \
--libdir=/usr/lib64/postgresql11 \
--with-includes=/usr/include/readline/ \
--enable-tap-tests \
--with-systemd \
--with-openssl \
--with-python \
--with-pam
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1642638261
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/postgresql11
cp %{_builddir}/postgresql-11.14/COPYRIGHT %{buildroot}/usr/share/package-licenses/postgresql11/b65c2d5331bc4d97b4b88e5a0cbf98c0452ea8d7
cp %{_builddir}/postgresql-11.14/src/backend/regex/COPYRIGHT %{buildroot}/usr/share/package-licenses/postgresql11/9ca05e9c70d9823e191d9b3876ecdeb57c53c725
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/postgresql11-install.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/postgresql11.service
mkdir -p %{buildroot}/usr/lib/tmpfiles.d
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/tmpfiles.d/postgresql11.conf
## install_append content
mkdir -p %{buildroot}/usr/bin
ln -s /usr/libexec/postgresql11/pg_ctl %{buildroot}/usr/bin/pg_ctl11
ln -s /usr/libexec/postgresql11/pg_dump %{buildroot}/usr/bin/pg_dump11
ln -s /usr/libexec/postgresql11/pg_dumpall %{buildroot}/usr/bin/pg_dumpall11
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib64/postgresql11/pgxs/config/install-sh
/usr/lib64/postgresql11/pgxs/config/missing
/usr/lib64/postgresql11/pgxs/src/Makefile.global
/usr/lib64/postgresql11/pgxs/src/Makefile.port
/usr/lib64/postgresql11/pgxs/src/Makefile.shlib
/usr/lib64/postgresql11/pgxs/src/makefiles/pgxs.mk
/usr/lib64/postgresql11/pgxs/src/nls-global.mk
/usr/lib64/postgresql11/pgxs/src/pl/plpython/regress-python3-mangle.mk
/usr/lib64/postgresql11/pgxs/src/test/perl/PostgresNode.pm
/usr/lib64/postgresql11/pgxs/src/test/perl/RecursiveCopy.pm
/usr/lib64/postgresql11/pgxs/src/test/perl/SimpleTee.pm
/usr/lib64/postgresql11/pgxs/src/test/perl/TestLib.pm
/usr/lib64/postgresql11/pgxs/src/test/regress/pg_regress
/usr/lib64/postgresql11/pkgconfig/libecpg.pc
/usr/lib64/postgresql11/pkgconfig/libecpg_compat.pc
/usr/lib64/postgresql11/pkgconfig/libpgtypes.pc
/usr/lib64/postgresql11/pkgconfig/libpq.pc

%files bin
%defattr(-,root,root,-)
/usr/bin/pg_ctl11
/usr/bin/pg_dump11
/usr/bin/pg_dumpall11

%files config
%defattr(-,root,root,-)
/usr/lib/tmpfiles.d/postgresql11.conf

%files data
%defattr(-,root,root,-)
/usr/share/postgresql11/conversion_create.sql
/usr/share/postgresql11/errcodes.txt
/usr/share/postgresql11/extension/plpgsql--1.0.sql
/usr/share/postgresql11/extension/plpgsql--unpackaged--1.0.sql
/usr/share/postgresql11/extension/plpgsql.control
/usr/share/postgresql11/extension/plpython3u--1.0.sql
/usr/share/postgresql11/extension/plpython3u--unpackaged--1.0.sql
/usr/share/postgresql11/extension/plpython3u.control
/usr/share/postgresql11/information_schema.sql
/usr/share/postgresql11/pg_hba.conf.sample
/usr/share/postgresql11/pg_ident.conf.sample
/usr/share/postgresql11/pg_service.conf.sample
/usr/share/postgresql11/postgres.bki
/usr/share/postgresql11/postgres.description
/usr/share/postgresql11/postgres.shdescription
/usr/share/postgresql11/postgresql.conf.sample
/usr/share/postgresql11/psqlrc.sample
/usr/share/postgresql11/recovery.conf.sample
/usr/share/postgresql11/snowball_create.sql
/usr/share/postgresql11/sql_features.txt
/usr/share/postgresql11/system_views.sql
/usr/share/postgresql11/timezone/Africa/Abidjan
/usr/share/postgresql11/timezone/Africa/Accra
/usr/share/postgresql11/timezone/Africa/Addis_Ababa
/usr/share/postgresql11/timezone/Africa/Algiers
/usr/share/postgresql11/timezone/Africa/Asmara
/usr/share/postgresql11/timezone/Africa/Asmera
/usr/share/postgresql11/timezone/Africa/Bamako
/usr/share/postgresql11/timezone/Africa/Bangui
/usr/share/postgresql11/timezone/Africa/Banjul
/usr/share/postgresql11/timezone/Africa/Bissau
/usr/share/postgresql11/timezone/Africa/Blantyre
/usr/share/postgresql11/timezone/Africa/Brazzaville
/usr/share/postgresql11/timezone/Africa/Bujumbura
/usr/share/postgresql11/timezone/Africa/Cairo
/usr/share/postgresql11/timezone/Africa/Casablanca
/usr/share/postgresql11/timezone/Africa/Ceuta
/usr/share/postgresql11/timezone/Africa/Conakry
/usr/share/postgresql11/timezone/Africa/Dakar
/usr/share/postgresql11/timezone/Africa/Dar_es_Salaam
/usr/share/postgresql11/timezone/Africa/Djibouti
/usr/share/postgresql11/timezone/Africa/Douala
/usr/share/postgresql11/timezone/Africa/El_Aaiun
/usr/share/postgresql11/timezone/Africa/Freetown
/usr/share/postgresql11/timezone/Africa/Gaborone
/usr/share/postgresql11/timezone/Africa/Harare
/usr/share/postgresql11/timezone/Africa/Johannesburg
/usr/share/postgresql11/timezone/Africa/Juba
/usr/share/postgresql11/timezone/Africa/Kampala
/usr/share/postgresql11/timezone/Africa/Khartoum
/usr/share/postgresql11/timezone/Africa/Kigali
/usr/share/postgresql11/timezone/Africa/Kinshasa
/usr/share/postgresql11/timezone/Africa/Lagos
/usr/share/postgresql11/timezone/Africa/Libreville
/usr/share/postgresql11/timezone/Africa/Lome
/usr/share/postgresql11/timezone/Africa/Luanda
/usr/share/postgresql11/timezone/Africa/Lubumbashi
/usr/share/postgresql11/timezone/Africa/Lusaka
/usr/share/postgresql11/timezone/Africa/Malabo
/usr/share/postgresql11/timezone/Africa/Maputo
/usr/share/postgresql11/timezone/Africa/Maseru
/usr/share/postgresql11/timezone/Africa/Mbabane
/usr/share/postgresql11/timezone/Africa/Mogadishu
/usr/share/postgresql11/timezone/Africa/Monrovia
/usr/share/postgresql11/timezone/Africa/Nairobi
/usr/share/postgresql11/timezone/Africa/Ndjamena
/usr/share/postgresql11/timezone/Africa/Niamey
/usr/share/postgresql11/timezone/Africa/Nouakchott
/usr/share/postgresql11/timezone/Africa/Ouagadougou
/usr/share/postgresql11/timezone/Africa/Porto-Novo
/usr/share/postgresql11/timezone/Africa/Sao_Tome
/usr/share/postgresql11/timezone/Africa/Timbuktu
/usr/share/postgresql11/timezone/Africa/Tripoli
/usr/share/postgresql11/timezone/Africa/Tunis
/usr/share/postgresql11/timezone/Africa/Windhoek
/usr/share/postgresql11/timezone/America/Adak
/usr/share/postgresql11/timezone/America/Anchorage
/usr/share/postgresql11/timezone/America/Anguilla
/usr/share/postgresql11/timezone/America/Antigua
/usr/share/postgresql11/timezone/America/Araguaina
/usr/share/postgresql11/timezone/America/Argentina/Buenos_Aires
/usr/share/postgresql11/timezone/America/Argentina/Catamarca
/usr/share/postgresql11/timezone/America/Argentina/ComodRivadavia
/usr/share/postgresql11/timezone/America/Argentina/Cordoba
/usr/share/postgresql11/timezone/America/Argentina/Jujuy
/usr/share/postgresql11/timezone/America/Argentina/La_Rioja
/usr/share/postgresql11/timezone/America/Argentina/Mendoza
/usr/share/postgresql11/timezone/America/Argentina/Rio_Gallegos
/usr/share/postgresql11/timezone/America/Argentina/Salta
/usr/share/postgresql11/timezone/America/Argentina/San_Juan
/usr/share/postgresql11/timezone/America/Argentina/San_Luis
/usr/share/postgresql11/timezone/America/Argentina/Tucuman
/usr/share/postgresql11/timezone/America/Argentina/Ushuaia
/usr/share/postgresql11/timezone/America/Aruba
/usr/share/postgresql11/timezone/America/Asuncion
/usr/share/postgresql11/timezone/America/Atikokan
/usr/share/postgresql11/timezone/America/Atka
/usr/share/postgresql11/timezone/America/Bahia
/usr/share/postgresql11/timezone/America/Bahia_Banderas
/usr/share/postgresql11/timezone/America/Barbados
/usr/share/postgresql11/timezone/America/Belem
/usr/share/postgresql11/timezone/America/Belize
/usr/share/postgresql11/timezone/America/Blanc-Sablon
/usr/share/postgresql11/timezone/America/Boa_Vista
/usr/share/postgresql11/timezone/America/Bogota
/usr/share/postgresql11/timezone/America/Boise
/usr/share/postgresql11/timezone/America/Buenos_Aires
/usr/share/postgresql11/timezone/America/Cambridge_Bay
/usr/share/postgresql11/timezone/America/Campo_Grande
/usr/share/postgresql11/timezone/America/Cancun
/usr/share/postgresql11/timezone/America/Caracas
/usr/share/postgresql11/timezone/America/Catamarca
/usr/share/postgresql11/timezone/America/Cayenne
/usr/share/postgresql11/timezone/America/Cayman
/usr/share/postgresql11/timezone/America/Chicago
/usr/share/postgresql11/timezone/America/Chihuahua
/usr/share/postgresql11/timezone/America/Coral_Harbour
/usr/share/postgresql11/timezone/America/Cordoba
/usr/share/postgresql11/timezone/America/Costa_Rica
/usr/share/postgresql11/timezone/America/Creston
/usr/share/postgresql11/timezone/America/Cuiaba
/usr/share/postgresql11/timezone/America/Curacao
/usr/share/postgresql11/timezone/America/Danmarkshavn
/usr/share/postgresql11/timezone/America/Dawson
/usr/share/postgresql11/timezone/America/Dawson_Creek
/usr/share/postgresql11/timezone/America/Denver
/usr/share/postgresql11/timezone/America/Detroit
/usr/share/postgresql11/timezone/America/Dominica
/usr/share/postgresql11/timezone/America/Edmonton
/usr/share/postgresql11/timezone/America/Eirunepe
/usr/share/postgresql11/timezone/America/El_Salvador
/usr/share/postgresql11/timezone/America/Ensenada
/usr/share/postgresql11/timezone/America/Fort_Nelson
/usr/share/postgresql11/timezone/America/Fort_Wayne
/usr/share/postgresql11/timezone/America/Fortaleza
/usr/share/postgresql11/timezone/America/Glace_Bay
/usr/share/postgresql11/timezone/America/Godthab
/usr/share/postgresql11/timezone/America/Goose_Bay
/usr/share/postgresql11/timezone/America/Grand_Turk
/usr/share/postgresql11/timezone/America/Grenada
/usr/share/postgresql11/timezone/America/Guadeloupe
/usr/share/postgresql11/timezone/America/Guatemala
/usr/share/postgresql11/timezone/America/Guayaquil
/usr/share/postgresql11/timezone/America/Guyana
/usr/share/postgresql11/timezone/America/Halifax
/usr/share/postgresql11/timezone/America/Havana
/usr/share/postgresql11/timezone/America/Hermosillo
/usr/share/postgresql11/timezone/America/Indiana/Indianapolis
/usr/share/postgresql11/timezone/America/Indiana/Knox
/usr/share/postgresql11/timezone/America/Indiana/Marengo
/usr/share/postgresql11/timezone/America/Indiana/Petersburg
/usr/share/postgresql11/timezone/America/Indiana/Tell_City
/usr/share/postgresql11/timezone/America/Indiana/Vevay
/usr/share/postgresql11/timezone/America/Indiana/Vincennes
/usr/share/postgresql11/timezone/America/Indiana/Winamac
/usr/share/postgresql11/timezone/America/Indianapolis
/usr/share/postgresql11/timezone/America/Inuvik
/usr/share/postgresql11/timezone/America/Iqaluit
/usr/share/postgresql11/timezone/America/Jamaica
/usr/share/postgresql11/timezone/America/Jujuy
/usr/share/postgresql11/timezone/America/Juneau
/usr/share/postgresql11/timezone/America/Kentucky/Louisville
/usr/share/postgresql11/timezone/America/Kentucky/Monticello
/usr/share/postgresql11/timezone/America/Knox_IN
/usr/share/postgresql11/timezone/America/Kralendijk
/usr/share/postgresql11/timezone/America/La_Paz
/usr/share/postgresql11/timezone/America/Lima
/usr/share/postgresql11/timezone/America/Los_Angeles
/usr/share/postgresql11/timezone/America/Louisville
/usr/share/postgresql11/timezone/America/Lower_Princes
/usr/share/postgresql11/timezone/America/Maceio
/usr/share/postgresql11/timezone/America/Managua
/usr/share/postgresql11/timezone/America/Manaus
/usr/share/postgresql11/timezone/America/Marigot
/usr/share/postgresql11/timezone/America/Martinique
/usr/share/postgresql11/timezone/America/Matamoros
/usr/share/postgresql11/timezone/America/Mazatlan
/usr/share/postgresql11/timezone/America/Mendoza
/usr/share/postgresql11/timezone/America/Menominee
/usr/share/postgresql11/timezone/America/Merida
/usr/share/postgresql11/timezone/America/Metlakatla
/usr/share/postgresql11/timezone/America/Mexico_City
/usr/share/postgresql11/timezone/America/Miquelon
/usr/share/postgresql11/timezone/America/Moncton
/usr/share/postgresql11/timezone/America/Monterrey
/usr/share/postgresql11/timezone/America/Montevideo
/usr/share/postgresql11/timezone/America/Montreal
/usr/share/postgresql11/timezone/America/Montserrat
/usr/share/postgresql11/timezone/America/Nassau
/usr/share/postgresql11/timezone/America/New_York
/usr/share/postgresql11/timezone/America/Nipigon
/usr/share/postgresql11/timezone/America/Nome
/usr/share/postgresql11/timezone/America/Noronha
/usr/share/postgresql11/timezone/America/North_Dakota/Beulah
/usr/share/postgresql11/timezone/America/North_Dakota/Center
/usr/share/postgresql11/timezone/America/North_Dakota/New_Salem
/usr/share/postgresql11/timezone/America/Nuuk
/usr/share/postgresql11/timezone/America/Ojinaga
/usr/share/postgresql11/timezone/America/Panama
/usr/share/postgresql11/timezone/America/Pangnirtung
/usr/share/postgresql11/timezone/America/Paramaribo
/usr/share/postgresql11/timezone/America/Phoenix
/usr/share/postgresql11/timezone/America/Port-au-Prince
/usr/share/postgresql11/timezone/America/Port_of_Spain
/usr/share/postgresql11/timezone/America/Porto_Acre
/usr/share/postgresql11/timezone/America/Porto_Velho
/usr/share/postgresql11/timezone/America/Puerto_Rico
/usr/share/postgresql11/timezone/America/Punta_Arenas
/usr/share/postgresql11/timezone/America/Rainy_River
/usr/share/postgresql11/timezone/America/Rankin_Inlet
/usr/share/postgresql11/timezone/America/Recife
/usr/share/postgresql11/timezone/America/Regina
/usr/share/postgresql11/timezone/America/Resolute
/usr/share/postgresql11/timezone/America/Rio_Branco
/usr/share/postgresql11/timezone/America/Rosario
/usr/share/postgresql11/timezone/America/Santa_Isabel
/usr/share/postgresql11/timezone/America/Santarem
/usr/share/postgresql11/timezone/America/Santiago
/usr/share/postgresql11/timezone/America/Santo_Domingo
/usr/share/postgresql11/timezone/America/Sao_Paulo
/usr/share/postgresql11/timezone/America/Scoresbysund
/usr/share/postgresql11/timezone/America/Shiprock
/usr/share/postgresql11/timezone/America/Sitka
/usr/share/postgresql11/timezone/America/St_Barthelemy
/usr/share/postgresql11/timezone/America/St_Johns
/usr/share/postgresql11/timezone/America/St_Kitts
/usr/share/postgresql11/timezone/America/St_Lucia
/usr/share/postgresql11/timezone/America/St_Thomas
/usr/share/postgresql11/timezone/America/St_Vincent
/usr/share/postgresql11/timezone/America/Swift_Current
/usr/share/postgresql11/timezone/America/Tegucigalpa
/usr/share/postgresql11/timezone/America/Thule
/usr/share/postgresql11/timezone/America/Thunder_Bay
/usr/share/postgresql11/timezone/America/Tijuana
/usr/share/postgresql11/timezone/America/Toronto
/usr/share/postgresql11/timezone/America/Tortola
/usr/share/postgresql11/timezone/America/Vancouver
/usr/share/postgresql11/timezone/America/Virgin
/usr/share/postgresql11/timezone/America/Whitehorse
/usr/share/postgresql11/timezone/America/Winnipeg
/usr/share/postgresql11/timezone/America/Yakutat
/usr/share/postgresql11/timezone/America/Yellowknife
/usr/share/postgresql11/timezone/Antarctica/Casey
/usr/share/postgresql11/timezone/Antarctica/Davis
/usr/share/postgresql11/timezone/Antarctica/DumontDUrville
/usr/share/postgresql11/timezone/Antarctica/Macquarie
/usr/share/postgresql11/timezone/Antarctica/Mawson
/usr/share/postgresql11/timezone/Antarctica/McMurdo
/usr/share/postgresql11/timezone/Antarctica/Palmer
/usr/share/postgresql11/timezone/Antarctica/Rothera
/usr/share/postgresql11/timezone/Antarctica/South_Pole
/usr/share/postgresql11/timezone/Antarctica/Syowa
/usr/share/postgresql11/timezone/Antarctica/Troll
/usr/share/postgresql11/timezone/Antarctica/Vostok
/usr/share/postgresql11/timezone/Arctic/Longyearbyen
/usr/share/postgresql11/timezone/Asia/Aden
/usr/share/postgresql11/timezone/Asia/Almaty
/usr/share/postgresql11/timezone/Asia/Amman
/usr/share/postgresql11/timezone/Asia/Anadyr
/usr/share/postgresql11/timezone/Asia/Aqtau
/usr/share/postgresql11/timezone/Asia/Aqtobe
/usr/share/postgresql11/timezone/Asia/Ashgabat
/usr/share/postgresql11/timezone/Asia/Ashkhabad
/usr/share/postgresql11/timezone/Asia/Atyrau
/usr/share/postgresql11/timezone/Asia/Baghdad
/usr/share/postgresql11/timezone/Asia/Bahrain
/usr/share/postgresql11/timezone/Asia/Baku
/usr/share/postgresql11/timezone/Asia/Bangkok
/usr/share/postgresql11/timezone/Asia/Barnaul
/usr/share/postgresql11/timezone/Asia/Beirut
/usr/share/postgresql11/timezone/Asia/Bishkek
/usr/share/postgresql11/timezone/Asia/Brunei
/usr/share/postgresql11/timezone/Asia/Calcutta
/usr/share/postgresql11/timezone/Asia/Chita
/usr/share/postgresql11/timezone/Asia/Choibalsan
/usr/share/postgresql11/timezone/Asia/Chongqing
/usr/share/postgresql11/timezone/Asia/Chungking
/usr/share/postgresql11/timezone/Asia/Colombo
/usr/share/postgresql11/timezone/Asia/Dacca
/usr/share/postgresql11/timezone/Asia/Damascus
/usr/share/postgresql11/timezone/Asia/Dhaka
/usr/share/postgresql11/timezone/Asia/Dili
/usr/share/postgresql11/timezone/Asia/Dubai
/usr/share/postgresql11/timezone/Asia/Dushanbe
/usr/share/postgresql11/timezone/Asia/Famagusta
/usr/share/postgresql11/timezone/Asia/Gaza
/usr/share/postgresql11/timezone/Asia/Harbin
/usr/share/postgresql11/timezone/Asia/Hebron
/usr/share/postgresql11/timezone/Asia/Ho_Chi_Minh
/usr/share/postgresql11/timezone/Asia/Hong_Kong
/usr/share/postgresql11/timezone/Asia/Hovd
/usr/share/postgresql11/timezone/Asia/Irkutsk
/usr/share/postgresql11/timezone/Asia/Istanbul
/usr/share/postgresql11/timezone/Asia/Jakarta
/usr/share/postgresql11/timezone/Asia/Jayapura
/usr/share/postgresql11/timezone/Asia/Jerusalem
/usr/share/postgresql11/timezone/Asia/Kabul
/usr/share/postgresql11/timezone/Asia/Kamchatka
/usr/share/postgresql11/timezone/Asia/Karachi
/usr/share/postgresql11/timezone/Asia/Kashgar
/usr/share/postgresql11/timezone/Asia/Kathmandu
/usr/share/postgresql11/timezone/Asia/Katmandu
/usr/share/postgresql11/timezone/Asia/Khandyga
/usr/share/postgresql11/timezone/Asia/Kolkata
/usr/share/postgresql11/timezone/Asia/Krasnoyarsk
/usr/share/postgresql11/timezone/Asia/Kuala_Lumpur
/usr/share/postgresql11/timezone/Asia/Kuching
/usr/share/postgresql11/timezone/Asia/Kuwait
/usr/share/postgresql11/timezone/Asia/Macao
/usr/share/postgresql11/timezone/Asia/Macau
/usr/share/postgresql11/timezone/Asia/Magadan
/usr/share/postgresql11/timezone/Asia/Makassar
/usr/share/postgresql11/timezone/Asia/Manila
/usr/share/postgresql11/timezone/Asia/Muscat
/usr/share/postgresql11/timezone/Asia/Nicosia
/usr/share/postgresql11/timezone/Asia/Novokuznetsk
/usr/share/postgresql11/timezone/Asia/Novosibirsk
/usr/share/postgresql11/timezone/Asia/Omsk
/usr/share/postgresql11/timezone/Asia/Oral
/usr/share/postgresql11/timezone/Asia/Phnom_Penh
/usr/share/postgresql11/timezone/Asia/Pontianak
/usr/share/postgresql11/timezone/Asia/Pyongyang
/usr/share/postgresql11/timezone/Asia/Qatar
/usr/share/postgresql11/timezone/Asia/Qostanay
/usr/share/postgresql11/timezone/Asia/Qyzylorda
/usr/share/postgresql11/timezone/Asia/Rangoon
/usr/share/postgresql11/timezone/Asia/Riyadh
/usr/share/postgresql11/timezone/Asia/Saigon
/usr/share/postgresql11/timezone/Asia/Sakhalin
/usr/share/postgresql11/timezone/Asia/Samarkand
/usr/share/postgresql11/timezone/Asia/Seoul
/usr/share/postgresql11/timezone/Asia/Shanghai
/usr/share/postgresql11/timezone/Asia/Singapore
/usr/share/postgresql11/timezone/Asia/Srednekolymsk
/usr/share/postgresql11/timezone/Asia/Taipei
/usr/share/postgresql11/timezone/Asia/Tashkent
/usr/share/postgresql11/timezone/Asia/Tbilisi
/usr/share/postgresql11/timezone/Asia/Tehran
/usr/share/postgresql11/timezone/Asia/Tel_Aviv
/usr/share/postgresql11/timezone/Asia/Thimbu
/usr/share/postgresql11/timezone/Asia/Thimphu
/usr/share/postgresql11/timezone/Asia/Tokyo
/usr/share/postgresql11/timezone/Asia/Tomsk
/usr/share/postgresql11/timezone/Asia/Ujung_Pandang
/usr/share/postgresql11/timezone/Asia/Ulaanbaatar
/usr/share/postgresql11/timezone/Asia/Ulan_Bator
/usr/share/postgresql11/timezone/Asia/Urumqi
/usr/share/postgresql11/timezone/Asia/Ust-Nera
/usr/share/postgresql11/timezone/Asia/Vientiane
/usr/share/postgresql11/timezone/Asia/Vladivostok
/usr/share/postgresql11/timezone/Asia/Yakutsk
/usr/share/postgresql11/timezone/Asia/Yangon
/usr/share/postgresql11/timezone/Asia/Yekaterinburg
/usr/share/postgresql11/timezone/Asia/Yerevan
/usr/share/postgresql11/timezone/Atlantic/Azores
/usr/share/postgresql11/timezone/Atlantic/Bermuda
/usr/share/postgresql11/timezone/Atlantic/Canary
/usr/share/postgresql11/timezone/Atlantic/Cape_Verde
/usr/share/postgresql11/timezone/Atlantic/Faeroe
/usr/share/postgresql11/timezone/Atlantic/Faroe
/usr/share/postgresql11/timezone/Atlantic/Jan_Mayen
/usr/share/postgresql11/timezone/Atlantic/Madeira
/usr/share/postgresql11/timezone/Atlantic/Reykjavik
/usr/share/postgresql11/timezone/Atlantic/South_Georgia
/usr/share/postgresql11/timezone/Atlantic/St_Helena
/usr/share/postgresql11/timezone/Atlantic/Stanley
/usr/share/postgresql11/timezone/Australia/ACT
/usr/share/postgresql11/timezone/Australia/Adelaide
/usr/share/postgresql11/timezone/Australia/Brisbane
/usr/share/postgresql11/timezone/Australia/Broken_Hill
/usr/share/postgresql11/timezone/Australia/Canberra
/usr/share/postgresql11/timezone/Australia/Currie
/usr/share/postgresql11/timezone/Australia/Darwin
/usr/share/postgresql11/timezone/Australia/Eucla
/usr/share/postgresql11/timezone/Australia/Hobart
/usr/share/postgresql11/timezone/Australia/LHI
/usr/share/postgresql11/timezone/Australia/Lindeman
/usr/share/postgresql11/timezone/Australia/Lord_Howe
/usr/share/postgresql11/timezone/Australia/Melbourne
/usr/share/postgresql11/timezone/Australia/NSW
/usr/share/postgresql11/timezone/Australia/North
/usr/share/postgresql11/timezone/Australia/Perth
/usr/share/postgresql11/timezone/Australia/Queensland
/usr/share/postgresql11/timezone/Australia/South
/usr/share/postgresql11/timezone/Australia/Sydney
/usr/share/postgresql11/timezone/Australia/Tasmania
/usr/share/postgresql11/timezone/Australia/Victoria
/usr/share/postgresql11/timezone/Australia/West
/usr/share/postgresql11/timezone/Australia/Yancowinna
/usr/share/postgresql11/timezone/Brazil/Acre
/usr/share/postgresql11/timezone/Brazil/DeNoronha
/usr/share/postgresql11/timezone/Brazil/East
/usr/share/postgresql11/timezone/Brazil/West
/usr/share/postgresql11/timezone/CET
/usr/share/postgresql11/timezone/CST6CDT
/usr/share/postgresql11/timezone/Canada/Atlantic
/usr/share/postgresql11/timezone/Canada/Central
/usr/share/postgresql11/timezone/Canada/Eastern
/usr/share/postgresql11/timezone/Canada/Mountain
/usr/share/postgresql11/timezone/Canada/Newfoundland
/usr/share/postgresql11/timezone/Canada/Pacific
/usr/share/postgresql11/timezone/Canada/Saskatchewan
/usr/share/postgresql11/timezone/Canada/Yukon
/usr/share/postgresql11/timezone/Chile/Continental
/usr/share/postgresql11/timezone/Chile/EasterIsland
/usr/share/postgresql11/timezone/Cuba
/usr/share/postgresql11/timezone/EET
/usr/share/postgresql11/timezone/EST
/usr/share/postgresql11/timezone/EST5EDT
/usr/share/postgresql11/timezone/Egypt
/usr/share/postgresql11/timezone/Eire
/usr/share/postgresql11/timezone/Etc/GMT
/usr/share/postgresql11/timezone/Etc/GMT+0
/usr/share/postgresql11/timezone/Etc/GMT+1
/usr/share/postgresql11/timezone/Etc/GMT+10
/usr/share/postgresql11/timezone/Etc/GMT+11
/usr/share/postgresql11/timezone/Etc/GMT+12
/usr/share/postgresql11/timezone/Etc/GMT+2
/usr/share/postgresql11/timezone/Etc/GMT+3
/usr/share/postgresql11/timezone/Etc/GMT+4
/usr/share/postgresql11/timezone/Etc/GMT+5
/usr/share/postgresql11/timezone/Etc/GMT+6
/usr/share/postgresql11/timezone/Etc/GMT+7
/usr/share/postgresql11/timezone/Etc/GMT+8
/usr/share/postgresql11/timezone/Etc/GMT+9
/usr/share/postgresql11/timezone/Etc/GMT-0
/usr/share/postgresql11/timezone/Etc/GMT-1
/usr/share/postgresql11/timezone/Etc/GMT-10
/usr/share/postgresql11/timezone/Etc/GMT-11
/usr/share/postgresql11/timezone/Etc/GMT-12
/usr/share/postgresql11/timezone/Etc/GMT-13
/usr/share/postgresql11/timezone/Etc/GMT-14
/usr/share/postgresql11/timezone/Etc/GMT-2
/usr/share/postgresql11/timezone/Etc/GMT-3
/usr/share/postgresql11/timezone/Etc/GMT-4
/usr/share/postgresql11/timezone/Etc/GMT-5
/usr/share/postgresql11/timezone/Etc/GMT-6
/usr/share/postgresql11/timezone/Etc/GMT-7
/usr/share/postgresql11/timezone/Etc/GMT-8
/usr/share/postgresql11/timezone/Etc/GMT-9
/usr/share/postgresql11/timezone/Etc/GMT0
/usr/share/postgresql11/timezone/Etc/Greenwich
/usr/share/postgresql11/timezone/Etc/UCT
/usr/share/postgresql11/timezone/Etc/UTC
/usr/share/postgresql11/timezone/Etc/Universal
/usr/share/postgresql11/timezone/Etc/Zulu
/usr/share/postgresql11/timezone/Europe/Amsterdam
/usr/share/postgresql11/timezone/Europe/Andorra
/usr/share/postgresql11/timezone/Europe/Astrakhan
/usr/share/postgresql11/timezone/Europe/Athens
/usr/share/postgresql11/timezone/Europe/Belfast
/usr/share/postgresql11/timezone/Europe/Belgrade
/usr/share/postgresql11/timezone/Europe/Berlin
/usr/share/postgresql11/timezone/Europe/Bratislava
/usr/share/postgresql11/timezone/Europe/Brussels
/usr/share/postgresql11/timezone/Europe/Bucharest
/usr/share/postgresql11/timezone/Europe/Budapest
/usr/share/postgresql11/timezone/Europe/Busingen
/usr/share/postgresql11/timezone/Europe/Chisinau
/usr/share/postgresql11/timezone/Europe/Copenhagen
/usr/share/postgresql11/timezone/Europe/Dublin
/usr/share/postgresql11/timezone/Europe/Gibraltar
/usr/share/postgresql11/timezone/Europe/Guernsey
/usr/share/postgresql11/timezone/Europe/Helsinki
/usr/share/postgresql11/timezone/Europe/Isle_of_Man
/usr/share/postgresql11/timezone/Europe/Istanbul
/usr/share/postgresql11/timezone/Europe/Jersey
/usr/share/postgresql11/timezone/Europe/Kaliningrad
/usr/share/postgresql11/timezone/Europe/Kiev
/usr/share/postgresql11/timezone/Europe/Kirov
/usr/share/postgresql11/timezone/Europe/Lisbon
/usr/share/postgresql11/timezone/Europe/Ljubljana
/usr/share/postgresql11/timezone/Europe/London
/usr/share/postgresql11/timezone/Europe/Luxembourg
/usr/share/postgresql11/timezone/Europe/Madrid
/usr/share/postgresql11/timezone/Europe/Malta
/usr/share/postgresql11/timezone/Europe/Mariehamn
/usr/share/postgresql11/timezone/Europe/Minsk
/usr/share/postgresql11/timezone/Europe/Monaco
/usr/share/postgresql11/timezone/Europe/Moscow
/usr/share/postgresql11/timezone/Europe/Nicosia
/usr/share/postgresql11/timezone/Europe/Oslo
/usr/share/postgresql11/timezone/Europe/Paris
/usr/share/postgresql11/timezone/Europe/Podgorica
/usr/share/postgresql11/timezone/Europe/Prague
/usr/share/postgresql11/timezone/Europe/Riga
/usr/share/postgresql11/timezone/Europe/Rome
/usr/share/postgresql11/timezone/Europe/Samara
/usr/share/postgresql11/timezone/Europe/San_Marino
/usr/share/postgresql11/timezone/Europe/Sarajevo
/usr/share/postgresql11/timezone/Europe/Saratov
/usr/share/postgresql11/timezone/Europe/Simferopol
/usr/share/postgresql11/timezone/Europe/Skopje
/usr/share/postgresql11/timezone/Europe/Sofia
/usr/share/postgresql11/timezone/Europe/Stockholm
/usr/share/postgresql11/timezone/Europe/Tallinn
/usr/share/postgresql11/timezone/Europe/Tirane
/usr/share/postgresql11/timezone/Europe/Tiraspol
/usr/share/postgresql11/timezone/Europe/Ulyanovsk
/usr/share/postgresql11/timezone/Europe/Uzhgorod
/usr/share/postgresql11/timezone/Europe/Vaduz
/usr/share/postgresql11/timezone/Europe/Vatican
/usr/share/postgresql11/timezone/Europe/Vienna
/usr/share/postgresql11/timezone/Europe/Vilnius
/usr/share/postgresql11/timezone/Europe/Volgograd
/usr/share/postgresql11/timezone/Europe/Warsaw
/usr/share/postgresql11/timezone/Europe/Zagreb
/usr/share/postgresql11/timezone/Europe/Zaporozhye
/usr/share/postgresql11/timezone/Europe/Zurich
/usr/share/postgresql11/timezone/Factory
/usr/share/postgresql11/timezone/GB
/usr/share/postgresql11/timezone/GB-Eire
/usr/share/postgresql11/timezone/GMT
/usr/share/postgresql11/timezone/GMT+0
/usr/share/postgresql11/timezone/GMT-0
/usr/share/postgresql11/timezone/GMT0
/usr/share/postgresql11/timezone/Greenwich
/usr/share/postgresql11/timezone/HST
/usr/share/postgresql11/timezone/Hongkong
/usr/share/postgresql11/timezone/Iceland
/usr/share/postgresql11/timezone/Indian/Antananarivo
/usr/share/postgresql11/timezone/Indian/Chagos
/usr/share/postgresql11/timezone/Indian/Christmas
/usr/share/postgresql11/timezone/Indian/Cocos
/usr/share/postgresql11/timezone/Indian/Comoro
/usr/share/postgresql11/timezone/Indian/Kerguelen
/usr/share/postgresql11/timezone/Indian/Mahe
/usr/share/postgresql11/timezone/Indian/Maldives
/usr/share/postgresql11/timezone/Indian/Mauritius
/usr/share/postgresql11/timezone/Indian/Mayotte
/usr/share/postgresql11/timezone/Indian/Reunion
/usr/share/postgresql11/timezone/Iran
/usr/share/postgresql11/timezone/Israel
/usr/share/postgresql11/timezone/Jamaica
/usr/share/postgresql11/timezone/Japan
/usr/share/postgresql11/timezone/Kwajalein
/usr/share/postgresql11/timezone/Libya
/usr/share/postgresql11/timezone/MET
/usr/share/postgresql11/timezone/MST
/usr/share/postgresql11/timezone/MST7MDT
/usr/share/postgresql11/timezone/Mexico/BajaNorte
/usr/share/postgresql11/timezone/Mexico/BajaSur
/usr/share/postgresql11/timezone/Mexico/General
/usr/share/postgresql11/timezone/NZ
/usr/share/postgresql11/timezone/NZ-CHAT
/usr/share/postgresql11/timezone/Navajo
/usr/share/postgresql11/timezone/PRC
/usr/share/postgresql11/timezone/PST8PDT
/usr/share/postgresql11/timezone/Pacific/Apia
/usr/share/postgresql11/timezone/Pacific/Auckland
/usr/share/postgresql11/timezone/Pacific/Bougainville
/usr/share/postgresql11/timezone/Pacific/Chatham
/usr/share/postgresql11/timezone/Pacific/Chuuk
/usr/share/postgresql11/timezone/Pacific/Easter
/usr/share/postgresql11/timezone/Pacific/Efate
/usr/share/postgresql11/timezone/Pacific/Enderbury
/usr/share/postgresql11/timezone/Pacific/Fakaofo
/usr/share/postgresql11/timezone/Pacific/Fiji
/usr/share/postgresql11/timezone/Pacific/Funafuti
/usr/share/postgresql11/timezone/Pacific/Galapagos
/usr/share/postgresql11/timezone/Pacific/Gambier
/usr/share/postgresql11/timezone/Pacific/Guadalcanal
/usr/share/postgresql11/timezone/Pacific/Guam
/usr/share/postgresql11/timezone/Pacific/Honolulu
/usr/share/postgresql11/timezone/Pacific/Johnston
/usr/share/postgresql11/timezone/Pacific/Kanton
/usr/share/postgresql11/timezone/Pacific/Kiritimati
/usr/share/postgresql11/timezone/Pacific/Kosrae
/usr/share/postgresql11/timezone/Pacific/Kwajalein
/usr/share/postgresql11/timezone/Pacific/Majuro
/usr/share/postgresql11/timezone/Pacific/Marquesas
/usr/share/postgresql11/timezone/Pacific/Midway
/usr/share/postgresql11/timezone/Pacific/Nauru
/usr/share/postgresql11/timezone/Pacific/Niue
/usr/share/postgresql11/timezone/Pacific/Norfolk
/usr/share/postgresql11/timezone/Pacific/Noumea
/usr/share/postgresql11/timezone/Pacific/Pago_Pago
/usr/share/postgresql11/timezone/Pacific/Palau
/usr/share/postgresql11/timezone/Pacific/Pitcairn
/usr/share/postgresql11/timezone/Pacific/Pohnpei
/usr/share/postgresql11/timezone/Pacific/Ponape
/usr/share/postgresql11/timezone/Pacific/Port_Moresby
/usr/share/postgresql11/timezone/Pacific/Rarotonga
/usr/share/postgresql11/timezone/Pacific/Saipan
/usr/share/postgresql11/timezone/Pacific/Samoa
/usr/share/postgresql11/timezone/Pacific/Tahiti
/usr/share/postgresql11/timezone/Pacific/Tarawa
/usr/share/postgresql11/timezone/Pacific/Tongatapu
/usr/share/postgresql11/timezone/Pacific/Truk
/usr/share/postgresql11/timezone/Pacific/Wake
/usr/share/postgresql11/timezone/Pacific/Wallis
/usr/share/postgresql11/timezone/Pacific/Yap
/usr/share/postgresql11/timezone/Poland
/usr/share/postgresql11/timezone/Portugal
/usr/share/postgresql11/timezone/ROC
/usr/share/postgresql11/timezone/ROK
/usr/share/postgresql11/timezone/Singapore
/usr/share/postgresql11/timezone/Turkey
/usr/share/postgresql11/timezone/UCT
/usr/share/postgresql11/timezone/US/Alaska
/usr/share/postgresql11/timezone/US/Aleutian
/usr/share/postgresql11/timezone/US/Arizona
/usr/share/postgresql11/timezone/US/Central
/usr/share/postgresql11/timezone/US/East-Indiana
/usr/share/postgresql11/timezone/US/Eastern
/usr/share/postgresql11/timezone/US/Hawaii
/usr/share/postgresql11/timezone/US/Indiana-Starke
/usr/share/postgresql11/timezone/US/Michigan
/usr/share/postgresql11/timezone/US/Mountain
/usr/share/postgresql11/timezone/US/Pacific
/usr/share/postgresql11/timezone/US/Samoa
/usr/share/postgresql11/timezone/UTC
/usr/share/postgresql11/timezone/Universal
/usr/share/postgresql11/timezone/W-SU
/usr/share/postgresql11/timezone/WET
/usr/share/postgresql11/timezone/Zulu
/usr/share/postgresql11/timezone/posixrules
/usr/share/postgresql11/timezonesets/Africa.txt
/usr/share/postgresql11/timezonesets/America.txt
/usr/share/postgresql11/timezonesets/Antarctica.txt
/usr/share/postgresql11/timezonesets/Asia.txt
/usr/share/postgresql11/timezonesets/Atlantic.txt
/usr/share/postgresql11/timezonesets/Australia
/usr/share/postgresql11/timezonesets/Australia.txt
/usr/share/postgresql11/timezonesets/Default
/usr/share/postgresql11/timezonesets/Etc.txt
/usr/share/postgresql11/timezonesets/Europe.txt
/usr/share/postgresql11/timezonesets/India
/usr/share/postgresql11/timezonesets/Indian.txt
/usr/share/postgresql11/timezonesets/Pacific.txt
/usr/share/postgresql11/tsearch_data/danish.stop
/usr/share/postgresql11/tsearch_data/dutch.stop
/usr/share/postgresql11/tsearch_data/english.stop
/usr/share/postgresql11/tsearch_data/finnish.stop
/usr/share/postgresql11/tsearch_data/french.stop
/usr/share/postgresql11/tsearch_data/german.stop
/usr/share/postgresql11/tsearch_data/hungarian.stop
/usr/share/postgresql11/tsearch_data/hunspell_sample.affix
/usr/share/postgresql11/tsearch_data/hunspell_sample_long.affix
/usr/share/postgresql11/tsearch_data/hunspell_sample_long.dict
/usr/share/postgresql11/tsearch_data/hunspell_sample_num.affix
/usr/share/postgresql11/tsearch_data/hunspell_sample_num.dict
/usr/share/postgresql11/tsearch_data/ispell_sample.affix
/usr/share/postgresql11/tsearch_data/ispell_sample.dict
/usr/share/postgresql11/tsearch_data/italian.stop
/usr/share/postgresql11/tsearch_data/norwegian.stop
/usr/share/postgresql11/tsearch_data/portuguese.stop
/usr/share/postgresql11/tsearch_data/russian.stop
/usr/share/postgresql11/tsearch_data/spanish.stop
/usr/share/postgresql11/tsearch_data/swedish.stop
/usr/share/postgresql11/tsearch_data/synonym_sample.syn
/usr/share/postgresql11/tsearch_data/thesaurus_sample.ths
/usr/share/postgresql11/tsearch_data/turkish.stop

%files dev
%defattr(-,root,root,-)
/usr/include/postgresql11/ecpg_config.h
/usr/include/postgresql11/ecpg_informix.h
/usr/include/postgresql11/ecpgerrno.h
/usr/include/postgresql11/ecpglib.h
/usr/include/postgresql11/ecpgtype.h
/usr/include/postgresql11/informix/esql/datetime.h
/usr/include/postgresql11/informix/esql/decimal.h
/usr/include/postgresql11/informix/esql/sqltypes.h
/usr/include/postgresql11/internal/c.h
/usr/include/postgresql11/internal/libpq-int.h
/usr/include/postgresql11/internal/libpq/pqcomm.h
/usr/include/postgresql11/internal/port.h
/usr/include/postgresql11/internal/postgres_fe.h
/usr/include/postgresql11/internal/pqexpbuffer.h
/usr/include/postgresql11/libpq-events.h
/usr/include/postgresql11/libpq-fe.h
/usr/include/postgresql11/libpq/libpq-fs.h
/usr/include/postgresql11/pg_config.h
/usr/include/postgresql11/pg_config_ext.h
/usr/include/postgresql11/pg_config_manual.h
/usr/include/postgresql11/pg_config_os.h
/usr/include/postgresql11/pgtypes.h
/usr/include/postgresql11/pgtypes_date.h
/usr/include/postgresql11/pgtypes_error.h
/usr/include/postgresql11/pgtypes_interval.h
/usr/include/postgresql11/pgtypes_numeric.h
/usr/include/postgresql11/pgtypes_timestamp.h
/usr/include/postgresql11/postgres_ext.h
/usr/include/postgresql11/server/access/amapi.h
/usr/include/postgresql11/server/access/amvalidate.h
/usr/include/postgresql11/server/access/attnum.h
/usr/include/postgresql11/server/access/brin.h
/usr/include/postgresql11/server/access/brin_internal.h
/usr/include/postgresql11/server/access/brin_page.h
/usr/include/postgresql11/server/access/brin_pageops.h
/usr/include/postgresql11/server/access/brin_revmap.h
/usr/include/postgresql11/server/access/brin_tuple.h
/usr/include/postgresql11/server/access/brin_xlog.h
/usr/include/postgresql11/server/access/bufmask.h
/usr/include/postgresql11/server/access/clog.h
/usr/include/postgresql11/server/access/commit_ts.h
/usr/include/postgresql11/server/access/genam.h
/usr/include/postgresql11/server/access/generic_xlog.h
/usr/include/postgresql11/server/access/gin.h
/usr/include/postgresql11/server/access/gin_private.h
/usr/include/postgresql11/server/access/ginblock.h
/usr/include/postgresql11/server/access/ginxlog.h
/usr/include/postgresql11/server/access/gist.h
/usr/include/postgresql11/server/access/gist_private.h
/usr/include/postgresql11/server/access/gistscan.h
/usr/include/postgresql11/server/access/gistxlog.h
/usr/include/postgresql11/server/access/hash.h
/usr/include/postgresql11/server/access/hash_xlog.h
/usr/include/postgresql11/server/access/heapam.h
/usr/include/postgresql11/server/access/heapam_xlog.h
/usr/include/postgresql11/server/access/hio.h
/usr/include/postgresql11/server/access/htup.h
/usr/include/postgresql11/server/access/htup_details.h
/usr/include/postgresql11/server/access/itup.h
/usr/include/postgresql11/server/access/multixact.h
/usr/include/postgresql11/server/access/nbtree.h
/usr/include/postgresql11/server/access/nbtxlog.h
/usr/include/postgresql11/server/access/parallel.h
/usr/include/postgresql11/server/access/printsimple.h
/usr/include/postgresql11/server/access/printtup.h
/usr/include/postgresql11/server/access/reloptions.h
/usr/include/postgresql11/server/access/relscan.h
/usr/include/postgresql11/server/access/rewriteheap.h
/usr/include/postgresql11/server/access/rmgr.h
/usr/include/postgresql11/server/access/rmgrlist.h
/usr/include/postgresql11/server/access/sdir.h
/usr/include/postgresql11/server/access/session.h
/usr/include/postgresql11/server/access/skey.h
/usr/include/postgresql11/server/access/slru.h
/usr/include/postgresql11/server/access/spgist.h
/usr/include/postgresql11/server/access/spgist_private.h
/usr/include/postgresql11/server/access/spgxlog.h
/usr/include/postgresql11/server/access/stratnum.h
/usr/include/postgresql11/server/access/subtrans.h
/usr/include/postgresql11/server/access/sysattr.h
/usr/include/postgresql11/server/access/timeline.h
/usr/include/postgresql11/server/access/transam.h
/usr/include/postgresql11/server/access/tsmapi.h
/usr/include/postgresql11/server/access/tupconvert.h
/usr/include/postgresql11/server/access/tupdesc.h
/usr/include/postgresql11/server/access/tupdesc_details.h
/usr/include/postgresql11/server/access/tupmacs.h
/usr/include/postgresql11/server/access/tuptoaster.h
/usr/include/postgresql11/server/access/twophase.h
/usr/include/postgresql11/server/access/twophase_rmgr.h
/usr/include/postgresql11/server/access/valid.h
/usr/include/postgresql11/server/access/visibilitymap.h
/usr/include/postgresql11/server/access/xact.h
/usr/include/postgresql11/server/access/xlog.h
/usr/include/postgresql11/server/access/xlog_internal.h
/usr/include/postgresql11/server/access/xlogdefs.h
/usr/include/postgresql11/server/access/xloginsert.h
/usr/include/postgresql11/server/access/xlogreader.h
/usr/include/postgresql11/server/access/xlogrecord.h
/usr/include/postgresql11/server/access/xlogutils.h
/usr/include/postgresql11/server/bootstrap/bootstrap.h
/usr/include/postgresql11/server/c.h
/usr/include/postgresql11/server/catalog/binary_upgrade.h
/usr/include/postgresql11/server/catalog/catalog.h
/usr/include/postgresql11/server/catalog/catversion.h
/usr/include/postgresql11/server/catalog/dependency.h
/usr/include/postgresql11/server/catalog/genbki.h
/usr/include/postgresql11/server/catalog/heap.h
/usr/include/postgresql11/server/catalog/index.h
/usr/include/postgresql11/server/catalog/indexing.h
/usr/include/postgresql11/server/catalog/namespace.h
/usr/include/postgresql11/server/catalog/objectaccess.h
/usr/include/postgresql11/server/catalog/objectaddress.h
/usr/include/postgresql11/server/catalog/opfam_internal.h
/usr/include/postgresql11/server/catalog/partition.h
/usr/include/postgresql11/server/catalog/pg_aggregate.h
/usr/include/postgresql11/server/catalog/pg_aggregate_d.h
/usr/include/postgresql11/server/catalog/pg_am.h
/usr/include/postgresql11/server/catalog/pg_am_d.h
/usr/include/postgresql11/server/catalog/pg_amop.h
/usr/include/postgresql11/server/catalog/pg_amop_d.h
/usr/include/postgresql11/server/catalog/pg_amproc.h
/usr/include/postgresql11/server/catalog/pg_amproc_d.h
/usr/include/postgresql11/server/catalog/pg_attrdef.h
/usr/include/postgresql11/server/catalog/pg_attrdef_d.h
/usr/include/postgresql11/server/catalog/pg_attribute.h
/usr/include/postgresql11/server/catalog/pg_attribute_d.h
/usr/include/postgresql11/server/catalog/pg_auth_members.h
/usr/include/postgresql11/server/catalog/pg_auth_members_d.h
/usr/include/postgresql11/server/catalog/pg_authid.h
/usr/include/postgresql11/server/catalog/pg_authid_d.h
/usr/include/postgresql11/server/catalog/pg_cast.h
/usr/include/postgresql11/server/catalog/pg_cast_d.h
/usr/include/postgresql11/server/catalog/pg_class.h
/usr/include/postgresql11/server/catalog/pg_class_d.h
/usr/include/postgresql11/server/catalog/pg_collation.h
/usr/include/postgresql11/server/catalog/pg_collation_d.h
/usr/include/postgresql11/server/catalog/pg_constraint.h
/usr/include/postgresql11/server/catalog/pg_constraint_d.h
/usr/include/postgresql11/server/catalog/pg_control.h
/usr/include/postgresql11/server/catalog/pg_conversion.h
/usr/include/postgresql11/server/catalog/pg_conversion_d.h
/usr/include/postgresql11/server/catalog/pg_database.h
/usr/include/postgresql11/server/catalog/pg_database_d.h
/usr/include/postgresql11/server/catalog/pg_db_role_setting.h
/usr/include/postgresql11/server/catalog/pg_db_role_setting_d.h
/usr/include/postgresql11/server/catalog/pg_default_acl.h
/usr/include/postgresql11/server/catalog/pg_default_acl_d.h
/usr/include/postgresql11/server/catalog/pg_depend.h
/usr/include/postgresql11/server/catalog/pg_depend_d.h
/usr/include/postgresql11/server/catalog/pg_description.h
/usr/include/postgresql11/server/catalog/pg_description_d.h
/usr/include/postgresql11/server/catalog/pg_enum.h
/usr/include/postgresql11/server/catalog/pg_enum_d.h
/usr/include/postgresql11/server/catalog/pg_event_trigger.h
/usr/include/postgresql11/server/catalog/pg_event_trigger_d.h
/usr/include/postgresql11/server/catalog/pg_extension.h
/usr/include/postgresql11/server/catalog/pg_extension_d.h
/usr/include/postgresql11/server/catalog/pg_foreign_data_wrapper.h
/usr/include/postgresql11/server/catalog/pg_foreign_data_wrapper_d.h
/usr/include/postgresql11/server/catalog/pg_foreign_server.h
/usr/include/postgresql11/server/catalog/pg_foreign_server_d.h
/usr/include/postgresql11/server/catalog/pg_foreign_table.h
/usr/include/postgresql11/server/catalog/pg_foreign_table_d.h
/usr/include/postgresql11/server/catalog/pg_index.h
/usr/include/postgresql11/server/catalog/pg_index_d.h
/usr/include/postgresql11/server/catalog/pg_inherits.h
/usr/include/postgresql11/server/catalog/pg_inherits_d.h
/usr/include/postgresql11/server/catalog/pg_init_privs.h
/usr/include/postgresql11/server/catalog/pg_init_privs_d.h
/usr/include/postgresql11/server/catalog/pg_language.h
/usr/include/postgresql11/server/catalog/pg_language_d.h
/usr/include/postgresql11/server/catalog/pg_largeobject.h
/usr/include/postgresql11/server/catalog/pg_largeobject_d.h
/usr/include/postgresql11/server/catalog/pg_largeobject_metadata.h
/usr/include/postgresql11/server/catalog/pg_largeobject_metadata_d.h
/usr/include/postgresql11/server/catalog/pg_namespace.h
/usr/include/postgresql11/server/catalog/pg_namespace_d.h
/usr/include/postgresql11/server/catalog/pg_opclass.h
/usr/include/postgresql11/server/catalog/pg_opclass_d.h
/usr/include/postgresql11/server/catalog/pg_operator.h
/usr/include/postgresql11/server/catalog/pg_operator_d.h
/usr/include/postgresql11/server/catalog/pg_opfamily.h
/usr/include/postgresql11/server/catalog/pg_opfamily_d.h
/usr/include/postgresql11/server/catalog/pg_partitioned_table.h
/usr/include/postgresql11/server/catalog/pg_partitioned_table_d.h
/usr/include/postgresql11/server/catalog/pg_pltemplate.h
/usr/include/postgresql11/server/catalog/pg_pltemplate_d.h
/usr/include/postgresql11/server/catalog/pg_policy.h
/usr/include/postgresql11/server/catalog/pg_policy_d.h
/usr/include/postgresql11/server/catalog/pg_proc.h
/usr/include/postgresql11/server/catalog/pg_proc_d.h
/usr/include/postgresql11/server/catalog/pg_publication.h
/usr/include/postgresql11/server/catalog/pg_publication_d.h
/usr/include/postgresql11/server/catalog/pg_publication_rel.h
/usr/include/postgresql11/server/catalog/pg_publication_rel_d.h
/usr/include/postgresql11/server/catalog/pg_range.h
/usr/include/postgresql11/server/catalog/pg_range_d.h
/usr/include/postgresql11/server/catalog/pg_replication_origin.h
/usr/include/postgresql11/server/catalog/pg_replication_origin_d.h
/usr/include/postgresql11/server/catalog/pg_rewrite.h
/usr/include/postgresql11/server/catalog/pg_rewrite_d.h
/usr/include/postgresql11/server/catalog/pg_seclabel.h
/usr/include/postgresql11/server/catalog/pg_seclabel_d.h
/usr/include/postgresql11/server/catalog/pg_sequence.h
/usr/include/postgresql11/server/catalog/pg_sequence_d.h
/usr/include/postgresql11/server/catalog/pg_shdepend.h
/usr/include/postgresql11/server/catalog/pg_shdepend_d.h
/usr/include/postgresql11/server/catalog/pg_shdescription.h
/usr/include/postgresql11/server/catalog/pg_shdescription_d.h
/usr/include/postgresql11/server/catalog/pg_shseclabel.h
/usr/include/postgresql11/server/catalog/pg_shseclabel_d.h
/usr/include/postgresql11/server/catalog/pg_statistic.h
/usr/include/postgresql11/server/catalog/pg_statistic_d.h
/usr/include/postgresql11/server/catalog/pg_statistic_ext.h
/usr/include/postgresql11/server/catalog/pg_statistic_ext_d.h
/usr/include/postgresql11/server/catalog/pg_subscription.h
/usr/include/postgresql11/server/catalog/pg_subscription_d.h
/usr/include/postgresql11/server/catalog/pg_subscription_rel.h
/usr/include/postgresql11/server/catalog/pg_subscription_rel_d.h
/usr/include/postgresql11/server/catalog/pg_tablespace.h
/usr/include/postgresql11/server/catalog/pg_tablespace_d.h
/usr/include/postgresql11/server/catalog/pg_transform.h
/usr/include/postgresql11/server/catalog/pg_transform_d.h
/usr/include/postgresql11/server/catalog/pg_trigger.h
/usr/include/postgresql11/server/catalog/pg_trigger_d.h
/usr/include/postgresql11/server/catalog/pg_ts_config.h
/usr/include/postgresql11/server/catalog/pg_ts_config_d.h
/usr/include/postgresql11/server/catalog/pg_ts_config_map.h
/usr/include/postgresql11/server/catalog/pg_ts_config_map_d.h
/usr/include/postgresql11/server/catalog/pg_ts_dict.h
/usr/include/postgresql11/server/catalog/pg_ts_dict_d.h
/usr/include/postgresql11/server/catalog/pg_ts_parser.h
/usr/include/postgresql11/server/catalog/pg_ts_parser_d.h
/usr/include/postgresql11/server/catalog/pg_ts_template.h
/usr/include/postgresql11/server/catalog/pg_ts_template_d.h
/usr/include/postgresql11/server/catalog/pg_type.h
/usr/include/postgresql11/server/catalog/pg_type_d.h
/usr/include/postgresql11/server/catalog/pg_user_mapping.h
/usr/include/postgresql11/server/catalog/pg_user_mapping_d.h
/usr/include/postgresql11/server/catalog/schemapg.h
/usr/include/postgresql11/server/catalog/storage.h
/usr/include/postgresql11/server/catalog/storage_xlog.h
/usr/include/postgresql11/server/catalog/toasting.h
/usr/include/postgresql11/server/commands/alter.h
/usr/include/postgresql11/server/commands/async.h
/usr/include/postgresql11/server/commands/cluster.h
/usr/include/postgresql11/server/commands/collationcmds.h
/usr/include/postgresql11/server/commands/comment.h
/usr/include/postgresql11/server/commands/conversioncmds.h
/usr/include/postgresql11/server/commands/copy.h
/usr/include/postgresql11/server/commands/createas.h
/usr/include/postgresql11/server/commands/dbcommands.h
/usr/include/postgresql11/server/commands/dbcommands_xlog.h
/usr/include/postgresql11/server/commands/defrem.h
/usr/include/postgresql11/server/commands/discard.h
/usr/include/postgresql11/server/commands/event_trigger.h
/usr/include/postgresql11/server/commands/explain.h
/usr/include/postgresql11/server/commands/extension.h
/usr/include/postgresql11/server/commands/lockcmds.h
/usr/include/postgresql11/server/commands/matview.h
/usr/include/postgresql11/server/commands/policy.h
/usr/include/postgresql11/server/commands/portalcmds.h
/usr/include/postgresql11/server/commands/prepare.h
/usr/include/postgresql11/server/commands/proclang.h
/usr/include/postgresql11/server/commands/progress.h
/usr/include/postgresql11/server/commands/publicationcmds.h
/usr/include/postgresql11/server/commands/schemacmds.h
/usr/include/postgresql11/server/commands/seclabel.h
/usr/include/postgresql11/server/commands/sequence.h
/usr/include/postgresql11/server/commands/subscriptioncmds.h
/usr/include/postgresql11/server/commands/tablecmds.h
/usr/include/postgresql11/server/commands/tablespace.h
/usr/include/postgresql11/server/commands/trigger.h
/usr/include/postgresql11/server/commands/typecmds.h
/usr/include/postgresql11/server/commands/user.h
/usr/include/postgresql11/server/commands/vacuum.h
/usr/include/postgresql11/server/commands/variable.h
/usr/include/postgresql11/server/commands/view.h
/usr/include/postgresql11/server/common/base64.h
/usr/include/postgresql11/server/common/config_info.h
/usr/include/postgresql11/server/common/connect.h
/usr/include/postgresql11/server/common/controldata_utils.h
/usr/include/postgresql11/server/common/fe_memutils.h
/usr/include/postgresql11/server/common/file_perm.h
/usr/include/postgresql11/server/common/file_utils.h
/usr/include/postgresql11/server/common/int.h
/usr/include/postgresql11/server/common/int128.h
/usr/include/postgresql11/server/common/ip.h
/usr/include/postgresql11/server/common/keywords.h
/usr/include/postgresql11/server/common/md5.h
/usr/include/postgresql11/server/common/pg_lzcompress.h
/usr/include/postgresql11/server/common/relpath.h
/usr/include/postgresql11/server/common/restricted_token.h
/usr/include/postgresql11/server/common/saslprep.h
/usr/include/postgresql11/server/common/scram-common.h
/usr/include/postgresql11/server/common/sha2.h
/usr/include/postgresql11/server/common/string.h
/usr/include/postgresql11/server/common/unicode_norm.h
/usr/include/postgresql11/server/common/unicode_norm_table.h
/usr/include/postgresql11/server/common/username.h
/usr/include/postgresql11/server/datatype/timestamp.h
/usr/include/postgresql11/server/dynloader.h
/usr/include/postgresql11/server/executor/execExpr.h
/usr/include/postgresql11/server/executor/execParallel.h
/usr/include/postgresql11/server/executor/execPartition.h
/usr/include/postgresql11/server/executor/execdebug.h
/usr/include/postgresql11/server/executor/execdesc.h
/usr/include/postgresql11/server/executor/executor.h
/usr/include/postgresql11/server/executor/functions.h
/usr/include/postgresql11/server/executor/hashjoin.h
/usr/include/postgresql11/server/executor/instrument.h
/usr/include/postgresql11/server/executor/nodeAgg.h
/usr/include/postgresql11/server/executor/nodeAppend.h
/usr/include/postgresql11/server/executor/nodeBitmapAnd.h
/usr/include/postgresql11/server/executor/nodeBitmapHeapscan.h
/usr/include/postgresql11/server/executor/nodeBitmapIndexscan.h
/usr/include/postgresql11/server/executor/nodeBitmapOr.h
/usr/include/postgresql11/server/executor/nodeCtescan.h
/usr/include/postgresql11/server/executor/nodeCustom.h
/usr/include/postgresql11/server/executor/nodeForeignscan.h
/usr/include/postgresql11/server/executor/nodeFunctionscan.h
/usr/include/postgresql11/server/executor/nodeGather.h
/usr/include/postgresql11/server/executor/nodeGatherMerge.h
/usr/include/postgresql11/server/executor/nodeGroup.h
/usr/include/postgresql11/server/executor/nodeHash.h
/usr/include/postgresql11/server/executor/nodeHashjoin.h
/usr/include/postgresql11/server/executor/nodeIndexonlyscan.h
/usr/include/postgresql11/server/executor/nodeIndexscan.h
/usr/include/postgresql11/server/executor/nodeLimit.h
/usr/include/postgresql11/server/executor/nodeLockRows.h
/usr/include/postgresql11/server/executor/nodeMaterial.h
/usr/include/postgresql11/server/executor/nodeMergeAppend.h
/usr/include/postgresql11/server/executor/nodeMergejoin.h
/usr/include/postgresql11/server/executor/nodeModifyTable.h
/usr/include/postgresql11/server/executor/nodeNamedtuplestorescan.h
/usr/include/postgresql11/server/executor/nodeNestloop.h
/usr/include/postgresql11/server/executor/nodeProjectSet.h
/usr/include/postgresql11/server/executor/nodeRecursiveunion.h
/usr/include/postgresql11/server/executor/nodeResult.h
/usr/include/postgresql11/server/executor/nodeSamplescan.h
/usr/include/postgresql11/server/executor/nodeSeqscan.h
/usr/include/postgresql11/server/executor/nodeSetOp.h
/usr/include/postgresql11/server/executor/nodeSort.h
/usr/include/postgresql11/server/executor/nodeSubplan.h
/usr/include/postgresql11/server/executor/nodeSubqueryscan.h
/usr/include/postgresql11/server/executor/nodeTableFuncscan.h
/usr/include/postgresql11/server/executor/nodeTidscan.h
/usr/include/postgresql11/server/executor/nodeUnique.h
/usr/include/postgresql11/server/executor/nodeValuesscan.h
/usr/include/postgresql11/server/executor/nodeWindowAgg.h
/usr/include/postgresql11/server/executor/nodeWorktablescan.h
/usr/include/postgresql11/server/executor/spi.h
/usr/include/postgresql11/server/executor/spi_priv.h
/usr/include/postgresql11/server/executor/tablefunc.h
/usr/include/postgresql11/server/executor/tqueue.h
/usr/include/postgresql11/server/executor/tstoreReceiver.h
/usr/include/postgresql11/server/executor/tuptable.h
/usr/include/postgresql11/server/fe_utils/conditional.h
/usr/include/postgresql11/server/fe_utils/connect.h
/usr/include/postgresql11/server/fe_utils/mbprint.h
/usr/include/postgresql11/server/fe_utils/print.h
/usr/include/postgresql11/server/fe_utils/psqlscan.h
/usr/include/postgresql11/server/fe_utils/psqlscan_int.h
/usr/include/postgresql11/server/fe_utils/simple_list.h
/usr/include/postgresql11/server/fe_utils/string_utils.h
/usr/include/postgresql11/server/fmgr.h
/usr/include/postgresql11/server/foreign/fdwapi.h
/usr/include/postgresql11/server/foreign/foreign.h
/usr/include/postgresql11/server/funcapi.h
/usr/include/postgresql11/server/getaddrinfo.h
/usr/include/postgresql11/server/getopt_long.h
/usr/include/postgresql11/server/jit/jit.h
/usr/include/postgresql11/server/jit/llvmjit.h
/usr/include/postgresql11/server/jit/llvmjit_emit.h
/usr/include/postgresql11/server/lib/binaryheap.h
/usr/include/postgresql11/server/lib/bipartite_match.h
/usr/include/postgresql11/server/lib/bloomfilter.h
/usr/include/postgresql11/server/lib/dshash.h
/usr/include/postgresql11/server/lib/hyperloglog.h
/usr/include/postgresql11/server/lib/ilist.h
/usr/include/postgresql11/server/lib/knapsack.h
/usr/include/postgresql11/server/lib/pairingheap.h
/usr/include/postgresql11/server/lib/rbtree.h
/usr/include/postgresql11/server/lib/simplehash.h
/usr/include/postgresql11/server/lib/stringinfo.h
/usr/include/postgresql11/server/libpq/auth.h
/usr/include/postgresql11/server/libpq/be-fsstubs.h
/usr/include/postgresql11/server/libpq/crypt.h
/usr/include/postgresql11/server/libpq/hba.h
/usr/include/postgresql11/server/libpq/ifaddr.h
/usr/include/postgresql11/server/libpq/libpq-be.h
/usr/include/postgresql11/server/libpq/libpq-fs.h
/usr/include/postgresql11/server/libpq/libpq.h
/usr/include/postgresql11/server/libpq/pqcomm.h
/usr/include/postgresql11/server/libpq/pqformat.h
/usr/include/postgresql11/server/libpq/pqmq.h
/usr/include/postgresql11/server/libpq/pqsignal.h
/usr/include/postgresql11/server/libpq/scram.h
/usr/include/postgresql11/server/mb/pg_wchar.h
/usr/include/postgresql11/server/miscadmin.h
/usr/include/postgresql11/server/nodes/bitmapset.h
/usr/include/postgresql11/server/nodes/execnodes.h
/usr/include/postgresql11/server/nodes/extensible.h
/usr/include/postgresql11/server/nodes/lockoptions.h
/usr/include/postgresql11/server/nodes/makefuncs.h
/usr/include/postgresql11/server/nodes/memnodes.h
/usr/include/postgresql11/server/nodes/nodeFuncs.h
/usr/include/postgresql11/server/nodes/nodes.h
/usr/include/postgresql11/server/nodes/params.h
/usr/include/postgresql11/server/nodes/parsenodes.h
/usr/include/postgresql11/server/nodes/pg_list.h
/usr/include/postgresql11/server/nodes/plannodes.h
/usr/include/postgresql11/server/nodes/primnodes.h
/usr/include/postgresql11/server/nodes/print.h
/usr/include/postgresql11/server/nodes/readfuncs.h
/usr/include/postgresql11/server/nodes/relation.h
/usr/include/postgresql11/server/nodes/replnodes.h
/usr/include/postgresql11/server/nodes/tidbitmap.h
/usr/include/postgresql11/server/nodes/value.h
/usr/include/postgresql11/server/optimizer/clauses.h
/usr/include/postgresql11/server/optimizer/cost.h
/usr/include/postgresql11/server/optimizer/geqo.h
/usr/include/postgresql11/server/optimizer/geqo_copy.h
/usr/include/postgresql11/server/optimizer/geqo_gene.h
/usr/include/postgresql11/server/optimizer/geqo_misc.h
/usr/include/postgresql11/server/optimizer/geqo_mutation.h
/usr/include/postgresql11/server/optimizer/geqo_pool.h
/usr/include/postgresql11/server/optimizer/geqo_random.h
/usr/include/postgresql11/server/optimizer/geqo_recombination.h
/usr/include/postgresql11/server/optimizer/geqo_selection.h
/usr/include/postgresql11/server/optimizer/joininfo.h
/usr/include/postgresql11/server/optimizer/orclauses.h
/usr/include/postgresql11/server/optimizer/paramassign.h
/usr/include/postgresql11/server/optimizer/pathnode.h
/usr/include/postgresql11/server/optimizer/paths.h
/usr/include/postgresql11/server/optimizer/placeholder.h
/usr/include/postgresql11/server/optimizer/plancat.h
/usr/include/postgresql11/server/optimizer/planmain.h
/usr/include/postgresql11/server/optimizer/planner.h
/usr/include/postgresql11/server/optimizer/predtest.h
/usr/include/postgresql11/server/optimizer/prep.h
/usr/include/postgresql11/server/optimizer/restrictinfo.h
/usr/include/postgresql11/server/optimizer/subselect.h
/usr/include/postgresql11/server/optimizer/tlist.h
/usr/include/postgresql11/server/optimizer/var.h
/usr/include/postgresql11/server/parser/analyze.h
/usr/include/postgresql11/server/parser/gram.h
/usr/include/postgresql11/server/parser/gramparse.h
/usr/include/postgresql11/server/parser/kwlist.h
/usr/include/postgresql11/server/parser/parse_agg.h
/usr/include/postgresql11/server/parser/parse_clause.h
/usr/include/postgresql11/server/parser/parse_coerce.h
/usr/include/postgresql11/server/parser/parse_collate.h
/usr/include/postgresql11/server/parser/parse_cte.h
/usr/include/postgresql11/server/parser/parse_enr.h
/usr/include/postgresql11/server/parser/parse_expr.h
/usr/include/postgresql11/server/parser/parse_func.h
/usr/include/postgresql11/server/parser/parse_node.h
/usr/include/postgresql11/server/parser/parse_oper.h
/usr/include/postgresql11/server/parser/parse_param.h
/usr/include/postgresql11/server/parser/parse_relation.h
/usr/include/postgresql11/server/parser/parse_target.h
/usr/include/postgresql11/server/parser/parse_type.h
/usr/include/postgresql11/server/parser/parse_utilcmd.h
/usr/include/postgresql11/server/parser/parser.h
/usr/include/postgresql11/server/parser/parsetree.h
/usr/include/postgresql11/server/parser/scanner.h
/usr/include/postgresql11/server/parser/scansup.h
/usr/include/postgresql11/server/partitioning/partbounds.h
/usr/include/postgresql11/server/partitioning/partdefs.h
/usr/include/postgresql11/server/partitioning/partprune.h
/usr/include/postgresql11/server/pg_config.h
/usr/include/postgresql11/server/pg_config_ext.h
/usr/include/postgresql11/server/pg_config_manual.h
/usr/include/postgresql11/server/pg_config_os.h
/usr/include/postgresql11/server/pg_getopt.h
/usr/include/postgresql11/server/pg_trace.h
/usr/include/postgresql11/server/pgstat.h
/usr/include/postgresql11/server/pgtar.h
/usr/include/postgresql11/server/pgtime.h
/usr/include/postgresql11/server/plpgsql.h
/usr/include/postgresql11/server/plpy_cursorobject.h
/usr/include/postgresql11/server/plpy_elog.h
/usr/include/postgresql11/server/plpy_exec.h
/usr/include/postgresql11/server/plpy_main.h
/usr/include/postgresql11/server/plpy_planobject.h
/usr/include/postgresql11/server/plpy_plpymodule.h
/usr/include/postgresql11/server/plpy_procedure.h
/usr/include/postgresql11/server/plpy_resultobject.h
/usr/include/postgresql11/server/plpy_spi.h
/usr/include/postgresql11/server/plpy_subxactobject.h
/usr/include/postgresql11/server/plpy_typeio.h
/usr/include/postgresql11/server/plpy_util.h
/usr/include/postgresql11/server/plpython.h
/usr/include/postgresql11/server/port.h
/usr/include/postgresql11/server/port/aix.h
/usr/include/postgresql11/server/port/atomics.h
/usr/include/postgresql11/server/port/atomics/arch-arm.h
/usr/include/postgresql11/server/port/atomics/arch-hppa.h
/usr/include/postgresql11/server/port/atomics/arch-ia64.h
/usr/include/postgresql11/server/port/atomics/arch-ppc.h
/usr/include/postgresql11/server/port/atomics/arch-x86.h
/usr/include/postgresql11/server/port/atomics/fallback.h
/usr/include/postgresql11/server/port/atomics/generic-acc.h
/usr/include/postgresql11/server/port/atomics/generic-gcc.h
/usr/include/postgresql11/server/port/atomics/generic-msvc.h
/usr/include/postgresql11/server/port/atomics/generic-sunpro.h
/usr/include/postgresql11/server/port/atomics/generic-xlc.h
/usr/include/postgresql11/server/port/atomics/generic.h
/usr/include/postgresql11/server/port/cygwin.h
/usr/include/postgresql11/server/port/darwin.h
/usr/include/postgresql11/server/port/freebsd.h
/usr/include/postgresql11/server/port/hpux.h
/usr/include/postgresql11/server/port/linux.h
/usr/include/postgresql11/server/port/netbsd.h
/usr/include/postgresql11/server/port/openbsd.h
/usr/include/postgresql11/server/port/pg_bswap.h
/usr/include/postgresql11/server/port/pg_crc32c.h
/usr/include/postgresql11/server/port/solaris.h
/usr/include/postgresql11/server/port/win32.h
/usr/include/postgresql11/server/port/win32/arpa/inet.h
/usr/include/postgresql11/server/port/win32/dlfcn.h
/usr/include/postgresql11/server/port/win32/grp.h
/usr/include/postgresql11/server/port/win32/netdb.h
/usr/include/postgresql11/server/port/win32/netinet/in.h
/usr/include/postgresql11/server/port/win32/pwd.h
/usr/include/postgresql11/server/port/win32/sys/socket.h
/usr/include/postgresql11/server/port/win32/sys/wait.h
/usr/include/postgresql11/server/port/win32_msvc/dirent.h
/usr/include/postgresql11/server/port/win32_msvc/sys/file.h
/usr/include/postgresql11/server/port/win32_msvc/sys/param.h
/usr/include/postgresql11/server/port/win32_msvc/sys/time.h
/usr/include/postgresql11/server/port/win32_msvc/unistd.h
/usr/include/postgresql11/server/port/win32_msvc/utime.h
/usr/include/postgresql11/server/port/win32_port.h
/usr/include/postgresql11/server/portability/instr_time.h
/usr/include/postgresql11/server/portability/mem.h
/usr/include/postgresql11/server/postgres.h
/usr/include/postgresql11/server/postgres_ext.h
/usr/include/postgresql11/server/postgres_fe.h
/usr/include/postgresql11/server/postmaster/autovacuum.h
/usr/include/postgresql11/server/postmaster/bgworker.h
/usr/include/postgresql11/server/postmaster/bgworker_internals.h
/usr/include/postgresql11/server/postmaster/bgwriter.h
/usr/include/postgresql11/server/postmaster/fork_process.h
/usr/include/postgresql11/server/postmaster/pgarch.h
/usr/include/postgresql11/server/postmaster/postmaster.h
/usr/include/postgresql11/server/postmaster/startup.h
/usr/include/postgresql11/server/postmaster/syslogger.h
/usr/include/postgresql11/server/postmaster/walwriter.h
/usr/include/postgresql11/server/regex/regcustom.h
/usr/include/postgresql11/server/regex/regerrs.h
/usr/include/postgresql11/server/regex/regex.h
/usr/include/postgresql11/server/regex/regexport.h
/usr/include/postgresql11/server/regex/regguts.h
/usr/include/postgresql11/server/replication/basebackup.h
/usr/include/postgresql11/server/replication/decode.h
/usr/include/postgresql11/server/replication/logical.h
/usr/include/postgresql11/server/replication/logicalfuncs.h
/usr/include/postgresql11/server/replication/logicallauncher.h
/usr/include/postgresql11/server/replication/logicalproto.h
/usr/include/postgresql11/server/replication/logicalrelation.h
/usr/include/postgresql11/server/replication/logicalworker.h
/usr/include/postgresql11/server/replication/message.h
/usr/include/postgresql11/server/replication/origin.h
/usr/include/postgresql11/server/replication/output_plugin.h
/usr/include/postgresql11/server/replication/pgoutput.h
/usr/include/postgresql11/server/replication/reorderbuffer.h
/usr/include/postgresql11/server/replication/slot.h
/usr/include/postgresql11/server/replication/snapbuild.h
/usr/include/postgresql11/server/replication/syncrep.h
/usr/include/postgresql11/server/replication/walreceiver.h
/usr/include/postgresql11/server/replication/walsender.h
/usr/include/postgresql11/server/replication/walsender_private.h
/usr/include/postgresql11/server/replication/worker_internal.h
/usr/include/postgresql11/server/rewrite/prs2lock.h
/usr/include/postgresql11/server/rewrite/rewriteDefine.h
/usr/include/postgresql11/server/rewrite/rewriteHandler.h
/usr/include/postgresql11/server/rewrite/rewriteManip.h
/usr/include/postgresql11/server/rewrite/rewriteRemove.h
/usr/include/postgresql11/server/rewrite/rewriteSupport.h
/usr/include/postgresql11/server/rewrite/rowsecurity.h
/usr/include/postgresql11/server/rusagestub.h
/usr/include/postgresql11/server/snowball/header.h
/usr/include/postgresql11/server/snowball/libstemmer/api.h
/usr/include/postgresql11/server/snowball/libstemmer/header.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_danish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_dutch.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_english.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_finnish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_french.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_german.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_hungarian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_italian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_norwegian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_porter.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_portuguese.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_spanish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_1_swedish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_ISO_8859_2_romanian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_KOI8_R_russian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_danish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_dutch.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_english.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_finnish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_french.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_german.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_hungarian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_italian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_norwegian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_porter.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_portuguese.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_romanian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_russian.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_spanish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_swedish.h
/usr/include/postgresql11/server/snowball/libstemmer/stem_UTF_8_turkish.h
/usr/include/postgresql11/server/statistics/extended_stats_internal.h
/usr/include/postgresql11/server/statistics/statistics.h
/usr/include/postgresql11/server/storage/backendid.h
/usr/include/postgresql11/server/storage/barrier.h
/usr/include/postgresql11/server/storage/block.h
/usr/include/postgresql11/server/storage/buf.h
/usr/include/postgresql11/server/storage/buf_internals.h
/usr/include/postgresql11/server/storage/buffile.h
/usr/include/postgresql11/server/storage/bufmgr.h
/usr/include/postgresql11/server/storage/bufpage.h
/usr/include/postgresql11/server/storage/checksum.h
/usr/include/postgresql11/server/storage/checksum_impl.h
/usr/include/postgresql11/server/storage/condition_variable.h
/usr/include/postgresql11/server/storage/copydir.h
/usr/include/postgresql11/server/storage/dsm.h
/usr/include/postgresql11/server/storage/dsm_impl.h
/usr/include/postgresql11/server/storage/fd.h
/usr/include/postgresql11/server/storage/freespace.h
/usr/include/postgresql11/server/storage/fsm_internals.h
/usr/include/postgresql11/server/storage/indexfsm.h
/usr/include/postgresql11/server/storage/ipc.h
/usr/include/postgresql11/server/storage/item.h
/usr/include/postgresql11/server/storage/itemid.h
/usr/include/postgresql11/server/storage/itemptr.h
/usr/include/postgresql11/server/storage/large_object.h
/usr/include/postgresql11/server/storage/latch.h
/usr/include/postgresql11/server/storage/lmgr.h
/usr/include/postgresql11/server/storage/lock.h
/usr/include/postgresql11/server/storage/lockdefs.h
/usr/include/postgresql11/server/storage/lwlock.h
/usr/include/postgresql11/server/storage/lwlocknames.h
/usr/include/postgresql11/server/storage/off.h
/usr/include/postgresql11/server/storage/pg_sema.h
/usr/include/postgresql11/server/storage/pg_shmem.h
/usr/include/postgresql11/server/storage/pmsignal.h
/usr/include/postgresql11/server/storage/predicate.h
/usr/include/postgresql11/server/storage/predicate_internals.h
/usr/include/postgresql11/server/storage/proc.h
/usr/include/postgresql11/server/storage/procarray.h
/usr/include/postgresql11/server/storage/proclist.h
/usr/include/postgresql11/server/storage/proclist_types.h
/usr/include/postgresql11/server/storage/procsignal.h
/usr/include/postgresql11/server/storage/reinit.h
/usr/include/postgresql11/server/storage/relfilenode.h
/usr/include/postgresql11/server/storage/s_lock.h
/usr/include/postgresql11/server/storage/sharedfileset.h
/usr/include/postgresql11/server/storage/shm_mq.h
/usr/include/postgresql11/server/storage/shm_toc.h
/usr/include/postgresql11/server/storage/shmem.h
/usr/include/postgresql11/server/storage/sinval.h
/usr/include/postgresql11/server/storage/sinvaladt.h
/usr/include/postgresql11/server/storage/smgr.h
/usr/include/postgresql11/server/storage/spin.h
/usr/include/postgresql11/server/storage/standby.h
/usr/include/postgresql11/server/storage/standbydefs.h
/usr/include/postgresql11/server/tcop/deparse_utility.h
/usr/include/postgresql11/server/tcop/dest.h
/usr/include/postgresql11/server/tcop/fastpath.h
/usr/include/postgresql11/server/tcop/pquery.h
/usr/include/postgresql11/server/tcop/tcopprot.h
/usr/include/postgresql11/server/tcop/utility.h
/usr/include/postgresql11/server/tsearch/dicts/regis.h
/usr/include/postgresql11/server/tsearch/dicts/spell.h
/usr/include/postgresql11/server/tsearch/ts_cache.h
/usr/include/postgresql11/server/tsearch/ts_locale.h
/usr/include/postgresql11/server/tsearch/ts_public.h
/usr/include/postgresql11/server/tsearch/ts_type.h
/usr/include/postgresql11/server/tsearch/ts_utils.h
/usr/include/postgresql11/server/utils/acl.h
/usr/include/postgresql11/server/utils/aclchk_internal.h
/usr/include/postgresql11/server/utils/array.h
/usr/include/postgresql11/server/utils/arrayaccess.h
/usr/include/postgresql11/server/utils/ascii.h
/usr/include/postgresql11/server/utils/attoptcache.h
/usr/include/postgresql11/server/utils/backend_random.h
/usr/include/postgresql11/server/utils/builtins.h
/usr/include/postgresql11/server/utils/bytea.h
/usr/include/postgresql11/server/utils/cash.h
/usr/include/postgresql11/server/utils/catcache.h
/usr/include/postgresql11/server/utils/combocid.h
/usr/include/postgresql11/server/utils/date.h
/usr/include/postgresql11/server/utils/datetime.h
/usr/include/postgresql11/server/utils/datum.h
/usr/include/postgresql11/server/utils/dsa.h
/usr/include/postgresql11/server/utils/dynahash.h
/usr/include/postgresql11/server/utils/dynamic_loader.h
/usr/include/postgresql11/server/utils/elog.h
/usr/include/postgresql11/server/utils/errcodes.h
/usr/include/postgresql11/server/utils/evtcache.h
/usr/include/postgresql11/server/utils/expandeddatum.h
/usr/include/postgresql11/server/utils/expandedrecord.h
/usr/include/postgresql11/server/utils/fmgroids.h
/usr/include/postgresql11/server/utils/fmgrprotos.h
/usr/include/postgresql11/server/utils/fmgrtab.h
/usr/include/postgresql11/server/utils/formatting.h
/usr/include/postgresql11/server/utils/freepage.h
/usr/include/postgresql11/server/utils/geo_decls.h
/usr/include/postgresql11/server/utils/guc.h
/usr/include/postgresql11/server/utils/guc_tables.h
/usr/include/postgresql11/server/utils/hashutils.h
/usr/include/postgresql11/server/utils/help_config.h
/usr/include/postgresql11/server/utils/hsearch.h
/usr/include/postgresql11/server/utils/index_selfuncs.h
/usr/include/postgresql11/server/utils/inet.h
/usr/include/postgresql11/server/utils/int8.h
/usr/include/postgresql11/server/utils/inval.h
/usr/include/postgresql11/server/utils/json.h
/usr/include/postgresql11/server/utils/jsonapi.h
/usr/include/postgresql11/server/utils/jsonb.h
/usr/include/postgresql11/server/utils/logtape.h
/usr/include/postgresql11/server/utils/lsyscache.h
/usr/include/postgresql11/server/utils/memdebug.h
/usr/include/postgresql11/server/utils/memutils.h
/usr/include/postgresql11/server/utils/nabstime.h
/usr/include/postgresql11/server/utils/numeric.h
/usr/include/postgresql11/server/utils/palloc.h
/usr/include/postgresql11/server/utils/partcache.h
/usr/include/postgresql11/server/utils/pg_crc.h
/usr/include/postgresql11/server/utils/pg_locale.h
/usr/include/postgresql11/server/utils/pg_lsn.h
/usr/include/postgresql11/server/utils/pg_rusage.h
/usr/include/postgresql11/server/utils/pidfile.h
/usr/include/postgresql11/server/utils/plancache.h
/usr/include/postgresql11/server/utils/portal.h
/usr/include/postgresql11/server/utils/probes.h
/usr/include/postgresql11/server/utils/ps_status.h
/usr/include/postgresql11/server/utils/queryenvironment.h
/usr/include/postgresql11/server/utils/rangetypes.h
/usr/include/postgresql11/server/utils/regproc.h
/usr/include/postgresql11/server/utils/rel.h
/usr/include/postgresql11/server/utils/relcache.h
/usr/include/postgresql11/server/utils/relfilenodemap.h
/usr/include/postgresql11/server/utils/relmapper.h
/usr/include/postgresql11/server/utils/relptr.h
/usr/include/postgresql11/server/utils/reltrigger.h
/usr/include/postgresql11/server/utils/resowner.h
/usr/include/postgresql11/server/utils/resowner_private.h
/usr/include/postgresql11/server/utils/rls.h
/usr/include/postgresql11/server/utils/ruleutils.h
/usr/include/postgresql11/server/utils/sampling.h
/usr/include/postgresql11/server/utils/selfuncs.h
/usr/include/postgresql11/server/utils/sharedtuplestore.h
/usr/include/postgresql11/server/utils/snapmgr.h
/usr/include/postgresql11/server/utils/snapshot.h
/usr/include/postgresql11/server/utils/sortsupport.h
/usr/include/postgresql11/server/utils/spccache.h
/usr/include/postgresql11/server/utils/syscache.h
/usr/include/postgresql11/server/utils/timeout.h
/usr/include/postgresql11/server/utils/timestamp.h
/usr/include/postgresql11/server/utils/tqual.h
/usr/include/postgresql11/server/utils/tuplesort.h
/usr/include/postgresql11/server/utils/tuplestore.h
/usr/include/postgresql11/server/utils/typcache.h
/usr/include/postgresql11/server/utils/tzparser.h
/usr/include/postgresql11/server/utils/uuid.h
/usr/include/postgresql11/server/utils/varbit.h
/usr/include/postgresql11/server/utils/varlena.h
/usr/include/postgresql11/server/utils/xml.h
/usr/include/postgresql11/server/windowapi.h
/usr/include/postgresql11/sql3types.h
/usr/include/postgresql11/sqlca.h
/usr/include/postgresql11/sqlda-compat.h
/usr/include/postgresql11/sqlda-native.h
/usr/include/postgresql11/sqlda.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/postgresql11/ascii_and_mic.so
/usr/lib64/postgresql11/cyrillic_and_mic.so
/usr/lib64/postgresql11/dict_snowball.so
/usr/lib64/postgresql11/euc2004_sjis2004.so
/usr/lib64/postgresql11/euc_cn_and_mic.so
/usr/lib64/postgresql11/euc_jp_and_sjis.so
/usr/lib64/postgresql11/euc_kr_and_mic.so
/usr/lib64/postgresql11/euc_tw_and_big5.so
/usr/lib64/postgresql11/latin2_and_win1250.so
/usr/lib64/postgresql11/latin_and_mic.so
/usr/lib64/postgresql11/libecpg.so
/usr/lib64/postgresql11/libecpg.so.6
/usr/lib64/postgresql11/libecpg.so.6.11
/usr/lib64/postgresql11/libecpg_compat.so
/usr/lib64/postgresql11/libecpg_compat.so.3
/usr/lib64/postgresql11/libecpg_compat.so.3.11
/usr/lib64/postgresql11/libpgtypes.so
/usr/lib64/postgresql11/libpgtypes.so.3
/usr/lib64/postgresql11/libpgtypes.so.3.11
/usr/lib64/postgresql11/libpq.so
/usr/lib64/postgresql11/libpq.so.5
/usr/lib64/postgresql11/libpq.so.5.11
/usr/lib64/postgresql11/libpqwalreceiver.so
/usr/lib64/postgresql11/pgoutput.so
/usr/lib64/postgresql11/plpgsql.so
/usr/lib64/postgresql11/plpython3.so
/usr/lib64/postgresql11/utf8_and_ascii.so
/usr/lib64/postgresql11/utf8_and_big5.so
/usr/lib64/postgresql11/utf8_and_cyrillic.so
/usr/lib64/postgresql11/utf8_and_euc2004.so
/usr/lib64/postgresql11/utf8_and_euc_cn.so
/usr/lib64/postgresql11/utf8_and_euc_jp.so
/usr/lib64/postgresql11/utf8_and_euc_kr.so
/usr/lib64/postgresql11/utf8_and_euc_tw.so
/usr/lib64/postgresql11/utf8_and_gb18030.so
/usr/lib64/postgresql11/utf8_and_gbk.so
/usr/lib64/postgresql11/utf8_and_iso8859.so
/usr/lib64/postgresql11/utf8_and_iso8859_1.so
/usr/lib64/postgresql11/utf8_and_johab.so
/usr/lib64/postgresql11/utf8_and_sjis.so
/usr/lib64/postgresql11/utf8_and_sjis2004.so
/usr/lib64/postgresql11/utf8_and_uhc.so
/usr/lib64/postgresql11/utf8_and_win.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/postgresql11/clusterdb
/usr/libexec/postgresql11/createdb
/usr/libexec/postgresql11/createuser
/usr/libexec/postgresql11/dropdb
/usr/libexec/postgresql11/dropuser
/usr/libexec/postgresql11/ecpg
/usr/libexec/postgresql11/initdb
/usr/libexec/postgresql11/pg_archivecleanup
/usr/libexec/postgresql11/pg_basebackup
/usr/libexec/postgresql11/pg_config
/usr/libexec/postgresql11/pg_controldata
/usr/libexec/postgresql11/pg_ctl
/usr/libexec/postgresql11/pg_dump
/usr/libexec/postgresql11/pg_dumpall
/usr/libexec/postgresql11/pg_isready
/usr/libexec/postgresql11/pg_receivewal
/usr/libexec/postgresql11/pg_recvlogical
/usr/libexec/postgresql11/pg_resetwal
/usr/libexec/postgresql11/pg_restore
/usr/libexec/postgresql11/pg_rewind
/usr/libexec/postgresql11/pg_test_fsync
/usr/libexec/postgresql11/pg_test_timing
/usr/libexec/postgresql11/pg_upgrade
/usr/libexec/postgresql11/pg_verify_checksums
/usr/libexec/postgresql11/pg_waldump
/usr/libexec/postgresql11/pgbench
/usr/libexec/postgresql11/postgres
/usr/libexec/postgresql11/postmaster
/usr/libexec/postgresql11/psql
/usr/libexec/postgresql11/reindexdb
/usr/libexec/postgresql11/vacuumdb

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/postgresql11/9ca05e9c70d9823e191d9b3876ecdeb57c53c725
/usr/share/package-licenses/postgresql11/b65c2d5331bc4d97b4b88e5a0cbf98c0452ea8d7

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/postgresql11-install.service
/usr/lib/systemd/system/postgresql11.service
